version: '3'
services:
  apiProfessor:
    build:
      context: ./
      dockerfile: Dockerfile
    image: apiprofessor
    container_name: apiProfessor
    volumes:
      - .:/src
    command: npm run dev
    env_file: .env
    environment:
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=$DB_HOST
      - NODE_ENV=$NODE_ENV
      - PORT=$PORT
    ports:
      - "3000:3000"
    volumes:
      - .:/src